AWSTemplateFormatVersion: '2010-09-09'
Description: WarehousePG Cluster Classic with Local Storage

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Deployment Scripts
        Parameters:
          - S3Bucket
      - Label:
          default: WarehousePG Configuration
        Parameters:
          - AccessToken
          - DatabaseName
      - Label:
          default: Compute
        Parameters:
          - NodeType
          - SegmentNodeCount
          - AMI
          - KeyPair
          - TimeZone
      - Label:
          default: Network
        Parameters:
          - InternetAccess
          - SSHCIDR
          - VPC
          - PrivateSubnet
          - PublicSubnet

Parameters:
  S3Bucket:
    Type: String
    Description: This bucket contains the unzipped scripts used for completing the deployment of WarehousePG
    Default: warehousepg-userdata-classic

  InternetAccess:
    Type: String
    Description: >-
      True means a Public IP address will be created for the Coordinator Node
      and ssh access on port 22 will be allowed to the CIDR range specified.
      Setting false means a bastion host will be needed to connect to the
      Coordinator node.
    Default: 'True'
    AllowedValues:
      - 'True'
      - 'False'

  SSHCIDR:
    Type: String
    Description: >-
      The CIDR range to allow SSH access. You can use 0.0.0.0/0 to allow all
      or a more restrictive range. This is only used if you enable
      InternetAccess and it is only applied to the SecurityGroup created for
      the PublicSubnet specified.
    Default: 0.0.0.0/0
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    ConstraintDescription: Must be a valid CIDR range.

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Choose an existing VPC with DNS support on.

  PrivateSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: >-
      The Private Subnet must be 1) in the above VPC 2) configured with
      outbound Internet access (Internet Gateway) 3) map IP Address on launch
      set on 4) ping, TCP, and UDP traffic allowed within the Private Subnet,
      and 5) in the same AZ as the PublicSubnet.

  PublicSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: >-
      Public facing Subnet for Coordinator Node if Internet Access is desired.
      If Internet Access is not desired, use the Private Subnet value. Public
      Subnet must be 1) in the above VPC, 2) map IP address on launch set on,
      3) configured with outbound Internet access, and 4) in the same AZ as
      the PrivateSubnet.

  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: >-
      Select an existing Amazon EC2 Key Pair. A Key Pair refers to the public
      and private keys used to access your nodes instead of a password.
    MinLength: '1'

  TimeZone:
    Type: String
    Description: Pick the TimeZone for the entire cluster.
    Default: America/New_York
    AllowedValues:
      - UTC
      - Asia/Tokyo
      - Asia/Seoul
      - Asia/Kolkata
      - Asia/Singapore
      - Australia/Sydney
      - America/Toronto
      - Europe/Berlin
      - Europe/Dublin
      - Europe/London
      - Europe/Paris
      - America/Sao_Paulo
      - America/New_York
      - America/Chicago
      - America/Los_Angeles
      - America/Denver

  AccessToken:
    Type: String
    Description: The access token for your EDB software
    MinLength: '32'
    MaxLength: '32'
    AllowedPattern: '^[a-zA-Z0-9]+$'
    ConstraintDescription: The access token is 32 characters long.

  AMI:
    Type: AWS::EC2::Image::Id
    Description: The ami id. The example on is Rocky Linux 9 for us-east-1.
    Default: ami-0f2425d4cce4e97dd

  DatabaseName:
    Type: String
    Description: The name of the default database in the cluster.
    Default: dev
    MinLength: '3'
    MaxLength: '63'
    AllowedPattern: '^[a-z]([a-z0-9])*?$'
    ConstraintDescription: >-
      Must be at least 3 characters long, lower case, start with a letter, and
      contain only letters and numbers.

  NodeType:
    Type: String
    Description: The Node Type.
    Default: i4i.2xlarge
    AllowedValues:
      - i4i.2xlarge
      - i4i.4xlarge
      - i4i.8xlarge
    ConstraintDescription: Must be a valid EC2 instance type

  SegmentNodeCount:
    Type: Number
    Description: >-
      Number of dedicated Segment Nodes in the cluster. Pick 0 for Single-Node
      deployments.
    Default: 0
    AllowedValues:
      - 0
      - 2
      - 4
      - 6
      - 8
      - 10
      - 12
      - 14
      - 16
      - 18
      - 20
      - 22
      - 24
      - 26
      - 28
      - 30
      - 32
      - 34
      - 36
      - 38
      - 40
      - 42
      - 44
      - 46
      - 48
      - 50
      - 52
      - 54
      - 56
      - 58
      - 60
      - 62
      - 64

Mappings:
  SegmentCountMapping:
    'i4i.2xlarge': { SegmentCount: '2' }
    'i4i.4xlarge': { SegmentCount: '4' }
    'i4i.8xlarge': { SegmentCount: '8' }

  ClusterCountMapping:
    '0':  { ClusterCount: '1',  Timeout: '1200' }
    '2':  { ClusterCount: '3',  Timeout: '1200' }
    '4':  { ClusterCount: '5',  Timeout: '1380' }
    '6':  { ClusterCount: '7',  Timeout: '1560' }
    '8':  { ClusterCount: '9',  Timeout: '1800' }
    '10': { ClusterCount: '11', Timeout: '1980' }
    '12': { ClusterCount: '13', Timeout: '2160' }
    '14': { ClusterCount: '15', Timeout: '2340' }
    '16': { ClusterCount: '17', Timeout: '2580' }
    '18': { ClusterCount: '19', Timeout: '2760' }
    '20': { ClusterCount: '21', Timeout: '2940' }
    '22': { ClusterCount: '23', Timeout: '3120' }
    '24': { ClusterCount: '25', Timeout: '3300' }
    '26': { ClusterCount: '27', Timeout: '3540' }
    '28': { ClusterCount: '29', Timeout: '3720' }
    '30': { ClusterCount: '31', Timeout: '3900' }
    '32': { ClusterCount: '33', Timeout: '4080' }
    '34': { ClusterCount: '35', Timeout: '4320' }
    '36': { ClusterCount: '37', Timeout: '4500' }
    '38': { ClusterCount: '39', Timeout: '4680' }
    '40': { ClusterCount: '41', Timeout: '4860' }
    '42': { ClusterCount: '43', Timeout: '5100' }
    '44': { ClusterCount: '45', Timeout: '5280' }
    '46': { ClusterCount: '47', Timeout: '5460' }
    '48': { ClusterCount: '49', Timeout: '5640' }
    '50': { ClusterCount: '51', Timeout: '5820' }
    '52': { ClusterCount: '53', Timeout: '6060' }
    '54': { ClusterCount: '55', Timeout: '6240' }
    '56': { ClusterCount: '57', Timeout: '6420' }
    '58': { ClusterCount: '59', Timeout: '6600' }
    '60': { ClusterCount: '61', Timeout: '6840' }
    '62': { ClusterCount: '63', Timeout: '7020' }
    '64': { ClusterCount: '65', Timeout: '7200' }

  ReleaseMapping:
    UserInfo:
      Admin: gpadmin
      #temporary password used only to exchange ssh keys
      AdminPass: ***REMOVED***

Conditions:
  PublicIP: !Equals [!Ref InternetAccess, 'True']
  MultiNodes: !Not [!Equals [!Ref SegmentNodeCount, '0']]

Resources:

  ClusterCompleteHandle:
    Type: AWS::CloudFormation::WaitConditionHandle

  ClusterCompleteCondition:
    Type: AWS::CloudFormation::WaitCondition
    DependsOn: CoordinatorNode
    Properties:
      Handle: !Ref ClusterCompleteHandle
      Timeout: !FindInMap [ClusterCountMapping, !Ref SegmentNodeCount, Timeout]
      Count: !FindInMap [ClusterCountMapping, !Ref SegmentNodeCount, ClusterCount]

  NodeIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: DescribeAccessEC2andCFN
          PolicyDocument:
            Statement:
              - Effect: Allow
                Resource: '*'
                Action:
                  - iam:PassRole
                  - ec2:CreateTags
                  - ec2:DescribeInstances
                  - ec2:DescribeInstanceStatus
                  - s3:ListAllMyBuckets
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref NodeIAMRole

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: PrivateSecurityGroup
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref AWS::StackName, PrivateSecurityGroup]]

  PrivateSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: Outbound access
      GroupId: !Ref PrivateSecurityGroup
      IpProtocol: '-1'
      CidrIp: 0.0.0.0/0

  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: PublicSecurityGroup
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref AWS::StackName, PublicSecurityGroup]]

  PublicSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: Outbound access
      GroupId: !Ref PublicSecurityGroup
      IpProtocol: '-1'
      CidrIp: 0.0.0.0/0

  PublicSecurityGroupSSH:
    Type: AWS::EC2::SecurityGroupIngress
    Condition: PublicIP
    Properties:
      Description: SSH access
      GroupId: !Ref PublicSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: !Ref SSHCIDR

  PrivateSecurityGroupPing:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ping access for the internal network.
      GroupId: !Ref PrivateSecurityGroup
      IpProtocol: icmp
      FromPort: 8
      ToPort: -1
      SourceSecurityGroupId: !Ref PrivateSecurityGroup

  PrivateSecurityGroupTCP:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: TCP access for the internal network.
      GroupId: !Ref PrivateSecurityGroup
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId: !Ref PrivateSecurityGroup

  PrivateSecurityGroupUDP:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: UDP access for the internal network.
      GroupId: !Ref PrivateSecurityGroup
      IpProtocol: udp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId: !Ref PrivateSecurityGroup

  CoordinatorNodeLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 32
              DeleteOnTermination: true
              VolumeType: gp2
          - DeviceName: /dev/sdz
            Ebs:
              VolumeSize: 32
              DeleteOnTermination: true
              VolumeType: gp2
              Encrypted: true
        EbsOptimized: true
        IamInstanceProfile:
          Arn: !Sub 'arn:aws:iam::${AWS::AccountId}:instance-profile/${InstanceProfile}'
        ImageId: !Ref AMI
        InstanceType: !Ref NodeType
        KeyName: !Ref KeyPair
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: !If [PublicIP, true, false]
            Groups:
              - !Ref PublicSecurityGroup
              - !Ref PrivateSecurityGroup
            SubnetId: !If [PublicIP, !Ref PublicSubnet, !Ref PrivateSubnet]
        Placement:
          Tenancy: default
        UserData:
          Fn::Base64:
            Fn::Sub:
              - |
                #!/bin/bash
                PATH+=":/usr/local/bin"
                export PATH
                mkdir -p /opt/edb/warehousepg
                echo 'STACK="${AWS::StackName}"' >> /opt/edb/warehousepg/config.sh
                echo 'COORDINATOR_HOST_IND="1"' >> /opt/edb/warehousepg/config.sh
                echo 'TIMEZONE="${TimeZone}"' >> /opt/edb/warehousepg/config.sh
                echo 'EDB_SUBSCRIPTION_TOKEN="${AccessToken}"' >> /opt/edb/warehousepg/config.sh
                echo 'DATABASE_NAME="${DatabaseName}"' >> /opt/edb/warehousepg/config.sh
                echo 'ADMIN="${Admin}"' >> /opt/edb/warehousepg/config.sh
                echo 'ADMIN_PASS="${AdminPass}"' >> /opt/edb/warehousepg/config.sh
                echo 'SIGNAL_COMPLETE_URL="${ClusterCompleteHandle}"' >> /opt/edb/warehousepg/config.sh
                echo 'INSTANCE_COUNT="${InstanceCount}"' >> /opt/edb/warehousepg/config.sh
                echo 'SEGMENT_COUNT="${SegmentCount}"' >> /opt/edb/warehousepg/config.sh
                #need newer aws cli version for s3files
                #dnf install awscli -y
                curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /opt/edb/warehousepg/awscliv2.zip
                echo "fastestmirror=True" >> /etc/dnf/dnf.conf
                dnf install unzip -y
                unzip /opt/edb/warehousepg/awscliv2.zip -d /opt/edb/warehousepg/
                /opt/edb/warehousepg/aws/install
                echo "export PATH=/usr/local/bin:\$PATH" >> /root/.bashrc
                aws s3 sync s3://${S3Bucket}/warehousepg/aws/ /opt/edb/warehousepg/
                chmod 755 /opt/edb/warehousepg/*.sh
                for i in $(ls /opt/edb/warehousepg/0*.sh); do ${!i}; done
              - Admin: !FindInMap [ReleaseMapping, UserInfo, Admin]
                #temporary password used only to exchange ssh keys
                AdminPass: !FindInMap [ReleaseMapping, UserInfo, AdminPass]
                InstanceCount: !FindInMap [ClusterCountMapping, !Ref SegmentNodeCount, ClusterCount]
                SegmentCount: !FindInMap [SegmentCountMapping, !Ref NodeType, SegmentCount ]


  CoordinatorNode:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref CoordinatorNodeLaunchTemplate
        Version: '1'
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref AWS::StackName, cdw]]

  SegmentNodesLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Condition: MultiNodes
    Properties:
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 32
              DeleteOnTermination: true
              VolumeType: gp2
          - DeviceName: /dev/sdz
            Ebs:
              VolumeSize: 32
              DeleteOnTermination: true
              VolumeType: gp2
              Encrypted: true
        EbsOptimized: true
        IamInstanceProfile:
          Arn: !Sub 'arn:aws:iam::${AWS::AccountId}:instance-profile/${InstanceProfile}'
        ImageId: !Ref AMI
        InstanceType: !Ref NodeType
        KeyName: !Ref KeyPair
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: false
            Groups:
              - !Ref PublicSecurityGroup
              - !Ref PrivateSecurityGroup
            SubnetId: !Ref PrivateSubnet
        Placement:
          Tenancy: default
        UserData:
          Fn::Base64:
            Fn::Sub:
              - |
                #!/bin/bash
                PATH+=":/usr/local/bin"
                export PATH
                mkdir -p /opt/edb/warehousepg
                echo 'STACK="${AWS::StackName}"' >> /opt/edb/warehousepg/config.sh
                echo 'COORDINATOR_HOST_IND="0"' >> /opt/edb/warehousepg/config.sh
                echo 'TIMEZONE="${TimeZone}"' >> /opt/edb/warehousepg/config.sh
                echo 'EDB_SUBSCRIPTION_TOKEN="${AccessToken}"' >> /opt/edb/warehousepg/config.sh
                echo 'DATABASE_NAME="${DatabaseName}"' >> /opt/edb/warehousepg/config.sh
                echo 'ADMIN="${Admin}"' >> /opt/edb/warehousepg/config.sh
                echo 'ADMIN_PASS="${AdminPass}"' >> /opt/edb/warehousepg/config.sh
                echo 'SIGNAL_COMPLETE_URL="${ClusterCompleteHandle}"' >> /opt/edb/warehousepg/config.sh
                echo 'INSTANCE_COUNT="${InstanceCount}"' >> /opt/edb/warehousepg/config.sh
                echo 'SEGMENT_COUNT="${SegmentCount}"' >> /opt/edb/warehousepg/config.sh
                #need newer aws cli version for s3files
                #dnf install awscli -y
                curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /opt/edb/warehousepg/awscliv2.zip
                echo "fastestmirror=True" >> /etc/dnf/dnf.conf
                dnf install unzip -y
                unzip /opt/edb/warehousepg/awscliv2.zip -d /opt/edb/warehousepg/
                /opt/edb/warehousepg/aws/install
                echo "export PATH=/usr/local/bin:\$PATH" >> /root/.bashrc
                aws s3 sync s3://${S3Bucket}/warehousepg/aws/ /opt/edb/warehousepg/
                chmod 755 /opt/edb/warehousepg/*.sh
                for i in $(ls /opt/edb/warehousepg/0*.sh); do ${!i}; done
              - Admin: !FindInMap [ReleaseMapping, UserInfo, Admin]
                #temporary password used only to exchange ssh keys
                AdminPass: !FindInMap [ReleaseMapping, UserInfo, AdminPass]
                InstanceCount: !FindInMap [ClusterCountMapping, !Ref SegmentNodeCount, ClusterCount]
                SegmentCount: !FindInMap [SegmentCountMapping, !Ref NodeType, SegmentCount ]

  SegmentNodes:
    Type: AWS::EC2::EC2Fleet
    Condition: MultiNodes
    Properties:
      Type: instant
      TargetCapacitySpecification:
        TotalTargetCapacity: !Ref SegmentNodeCount
        DefaultTargetCapacityType: on-demand
      LaunchTemplateConfigs:
        - LaunchTemplateSpecification:
            LaunchTemplateId: !Ref SegmentNodesLaunchTemplate
            Version: '1'
      TagSpecifications:
        - ResourceType: instance
          Tags:
            - Key: Name
              Value: !Ref AWS::StackName
